FROM nodered/node-red:latest

# Install node-red-contrib-influxdb for InfluxDB integration
RUN npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-influxdb
